version: "3"
services:
  node-0:
    image: wildfire
    networks:
      - net
    environment:
      NEIGHBORS_LIST: 'queue-6,queue-1,queue-9,queue-2,queue-7,queue-4,queue-8,queue-3,queue-5'
      QUEUE: 'queue-0'
      DEAD: 'false'
      NUM_VECTORS: 8
      URL_AMQP: 'amqps://kstpiasp:UtRFLlT5f2OicdJ6R04uHVni2R2U5tru@rat.rmq2.cloudamqp.com/kstpiasp'
    container_name: node-0
    volumes:
      - c:\Users\paolo\Documents\Big Data Management\the-price-of-validity\results:/app/results
  node-1:
    image: wildfire
    networks:
      - net
    environment:
      NEIGHBORS_LIST: 'queue-0,queue-2,queue-9,queue-6,queue-4,queue-3'
      QUEUE: 'queue-1'
      DEAD: 'false'
      NUM_VECTORS: 8
      URL_AMQP: 'amqps://kstpiasp:UtRFLlT5f2OicdJ6R04uHVni2R2U5tru@rat.rmq2.cloudamqp.com/kstpiasp'
    container_name: node-1
    volumes:
      - c:\Users\paolo\Documents\Big Data Management\the-price-of-validity\results:/app/results
  node-2:
    image: wildfire
    networks:
      - net
    environment:
      NEIGHBORS_LIST: 'queue-0,queue-1,queue-7,queue-4,queue-9,queue-8,queue-3,queue-5,queue-6'
      QUEUE: 'queue-2'
      DEAD: 'false'
      NUM_VECTORS: 8
      URL_AMQP: 'amqps://kstpiasp:UtRFLlT5f2OicdJ6R04uHVni2R2U5tru@rat.rmq2.cloudamqp.com/kstpiasp'
    container_name: node-2
    volumes:
      - c:\Users\paolo\Documents\Big Data Management\the-price-of-validity\results:/app/results
  node-3:
    image: wildfire
    networks:
      - net
    environment:
      NEIGHBORS_LIST: 'queue-0,queue-2,queue-8,queue-6,queue-1'
      QUEUE: 'queue-3'
      DEAD: 'false'
      NUM_VECTORS: 8
      URL_AMQP: 'amqps://kstpiasp:UtRFLlT5f2OicdJ6R04uHVni2R2U5tru@rat.rmq2.cloudamqp.com/kstpiasp'
    container_name: node-3
    volumes:
      - c:\Users\paolo\Documents\Big Data Management\the-price-of-validity\results:/app/results
  node-4:
    image: wildfire
    networks:
      - net
    environment:
      NEIGHBORS_LIST: 'queue-0,queue-1,queue-2,queue-8,queue-9'
      QUEUE: 'queue-4'
      DEAD: 'false'
      NUM_VECTORS: 8
      URL_AMQP: 'amqps://kstpiasp:UtRFLlT5f2OicdJ6R04uHVni2R2U5tru@rat.rmq2.cloudamqp.com/kstpiasp'
    container_name: node-4
    volumes:
      - c:\Users\paolo\Documents\Big Data Management\the-price-of-validity\results:/app/results
  node-5:
    image: wildfire
    networks:
      - net
    environment:
      NEIGHBORS_LIST: 'queue-2,queue-0'
      QUEUE: 'queue-5'
      DEAD: 'false'
      NUM_VECTORS: 8
      URL_AMQP: 'amqps://kstpiasp:UtRFLlT5f2OicdJ6R04uHVni2R2U5tru@rat.rmq2.cloudamqp.com/kstpiasp'
    container_name: node-5
    volumes:
      - c:\Users\paolo\Documents\Big Data Management\the-price-of-validity\results:/app/results
  node-6:
    image: wildfire
    networks:
      - net
    environment:
      NEIGHBORS_LIST: 'queue-0,queue-1,queue-2,queue-3'
      QUEUE: 'queue-6'
      DEAD: 'false'
      NUM_VECTORS: 8
      URL_AMQP: 'amqps://kstpiasp:UtRFLlT5f2OicdJ6R04uHVni2R2U5tru@rat.rmq2.cloudamqp.com/kstpiasp'
    container_name: node-6
    volumes:
      - c:\Users\paolo\Documents\Big Data Management\the-price-of-validity\results:/app/results
  node-7:
    image: wildfire
    networks:
      - net
    environment:
      NEIGHBORS_LIST: 'queue-0,queue-2'
      QUEUE: 'queue-7'
      DEAD: 'false'
      NUM_VECTORS: 8
      URL_AMQP: 'amqps://kstpiasp:UtRFLlT5f2OicdJ6R04uHVni2R2U5tru@rat.rmq2.cloudamqp.com/kstpiasp'
    container_name: node-7
    volumes:
      - c:\Users\paolo\Documents\Big Data Management\the-price-of-validity\results:/app/results
  node-8:
    image: wildfire
    networks:
      - net
    environment:
      NEIGHBORS_LIST: 'queue-0,queue-2,queue-3,queue-4'
      QUEUE: 'queue-8'
      DEAD: 'false'
      NUM_VECTORS: 8
      URL_AMQP: 'amqps://kstpiasp:UtRFLlT5f2OicdJ6R04uHVni2R2U5tru@rat.rmq2.cloudamqp.com/kstpiasp'
    container_name: node-8
    volumes:
      - c:\Users\paolo\Documents\Big Data Management\the-price-of-validity\results:/app/results
  node-9:
    image: wildfire
    networks:
      - net
    environment:
      NEIGHBORS_LIST: 'queue-0,queue-1,queue-2,queue-4'
      QUEUE: 'queue-9'
      DEAD: 'false'
      NUM_VECTORS: 8
      URL_AMQP: 'amqps://kstpiasp:UtRFLlT5f2OicdJ6R04uHVni2R2U5tru@rat.rmq2.cloudamqp.com/kstpiasp'
    container_name: node-9
    volumes:
      - c:\Users\paolo\Documents\Big Data Management\the-price-of-validity\results:/app/results
networks:
  net:
    driver: bridge
